version: "3.8"

services:
    # Application
    app:
        container_name: entornos-app
        build:
            args:
                user: entornos-user
                uid: 1000
            context: .
            dockerfile: ./docker/app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - database
        networks:
            - app-network

    # Web Server
    web:
        container_name: entornos-webserver
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        ports:
            - 8000:80
        networks:
            - app-network

    # Database
    database:
        container_name: entornos-db
        image: mysql:8.0.27
        volumes:
            - dbdata:/var/lib/mysql-files
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        expose:
            - ${DB_PORT}
        ports:
            - 3306:${DB_PORT}
        networks:
            - app-network

    # Database management
    pma:
        container_name: entornos-pma
        image: phpmyadmin/phpmyadmin:5.1.1
        environment:
            - PMA_HOST=database
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_PORT=${DB_PORT}
        depends_on:
            - database
        ports:
            - 8080:80
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
